### ISSUE TITLE
Lab 2 Report Feedback

### ISSUE THREAD

**Issue by enzohnnn** [k3alvare/cse15l-lab-reports#2]
**Bug/Input 1**
- [X] Commit screenshot for bug/input 1
- [X] Link to test file for bug/input 1
- [X] Symptom shown as command + output for bug/input 1
- [X] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [X] Commit screenshot for bug/input 2
- [X] Link to test file for bug/input 2
- [X] Symptom shown as command + output for bug/input 2
- [X] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [X] Commit screenshot for bug/input 3
- [X] Link to test file for bug/input 3
- [X] Symptom shown as command + output for bug/input 3
- [X] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
Well done. Everything looks good, easy to read with good descriptions of your problems and how you fixed them. Keep up the good work.

Feel free to comment below if you have any questions about the rubric/feedback.

**Comment by k3alvare** [comment]
Im glad everything looks good and easy, just how I wanted it to be!
